CREATE TABLE `lfsdb`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod` INT(4) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `color` VARCHAR(10) NOT NULL,
  `size` VARCHAR(3) NOT NULL,
  `amount` INT(5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cod_UNIQUE` (`cod` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));